# .github/workflows/build-temurin-android.yml
name: Build Temurin JDK 21 for Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Cross-compile JDK 21 for Android

    steps:
    - name: Checkout temurin-build
      uses: actions/checkout@v4
      with:
        repository: adoptium/temurin-build
        ref: master
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential autoconf zip unzip libx11-dev libxext-dev \
          libxrender-dev libxtst-dev libxt-dev libasound2-dev libcups2-dev \
          libfreetype6-dev libfontconfig1-dev libxrandr-dev libxinerama-dev \
          pkg-config ccache git wget curl python3 xz-utils \
          libpng-dev libjpeg-dev libgif-dev libharfbuzz-dev libffi-dev

    - name: Download Android NDK r25c
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip -q android-ndk-r25c-linux.zip
        mv android-ndk-r25c $HOME/android-ndk

    - name: Set environment variables
      run: |
        echo "ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV
        echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
        echo "$JAVA_HOME/bin" >> $GITHUB_PATH
        ls -l $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot
        ls -l $JAVA_HOME

    - name: Build JDK 21 for Android (aarch64)
      run: |
        ./makejdk-any-platform.sh jdk \
          --build-variant normal \
#          --configure-args "--with-boot-jdk=$JAVA_HOME --disable-precompiled-headers --disable-warnings-as-errors --enable-option-checking=fatal --enable-headless-only=yes --with-jvm-variants=server --with-jvm-features=-dtrace,-zero,-vm-structs,-epsilongc --with-native-debug-symbols=external --with-debug-level=release --x-libraries=/usr/lib --openjdk-target=aarch64-linux-android --with-sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot" 
    - name: Upload OpenJDK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openjdk21-android-build
        path: |
          workspace/target/OpenJDK-jdk.tar.gz
          workspace/target/OpenJDK-static-libs-glibc.tar.gz
          workspace/target/OpenJDK-testimage.tar.gz
